import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import User from '../models/User.model';
import Book from '../models/Book.model';
import ExamTag from '../models/ExamTag.model';
import Address from '../models/Address.model';
import env from '../config/env';

const cover = (isbn: string) => `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;
const olid  = (id: string)   => `https://covers.openlibrary.org/b/id/${id}-L.jpg`;

const USERS = [
  { name: 'Admin Folio',   email: 'admin@folio.in',    password: 'Admin@123', role: 'admin', countryCode: 'IN', currencyCode: 'INR' },
  { name: 'Rahul Sharma',  email: 'rahul@example.in',  password: 'Pass@1234', role: 'user',  countryCode: 'IN', currencyCode: 'INR' },
  { name: 'Priya Verma',   email: 'priya@example.in',  password: 'Pass@1234', role: 'user',  countryCode: 'IN', currencyCode: 'INR' },
  { name: 'Arjun Mehta',   email: 'arjun@example.in',  password: 'Pass@1234', role: 'user',  countryCode: 'IN', currencyCode: 'INR' },
  { name: 'Sneha Iyer',    email: 'sneha@example.in',  password: 'Pass@1234', role: 'user',  countryCode: 'IN', currencyCode: 'INR' },
  { name: 'Vikram Patel',  email: 'vikram@example.in', password: 'Pass@1234', role: 'user',  countryCode: 'IN', currencyCode: 'INR' },
  { name: 'Ananya Roy',    email: 'ananya@example.in', password: 'Pass@1234', role: 'user',  countryCode: 'IN', currencyCode: 'INR' },
  { name: 'Karan Singh',   email: 'karan@example.in',  password: 'Pass@1234', role: 'user',  countryCode: 'IN', currencyCode: 'INR' },
  { name: 'Meera Nair',    email: 'meera@example.in',  password: 'Pass@1234', role: 'user',  countryCode: 'IN', currencyCode: 'INR' },
  { name: 'Rohan Gupta',   email: 'rohan@example.in',  password: 'Pass@1234', role: 'user',  countryCode: 'IN', currencyCode: 'INR' },
];

const EXAM_TAGS = [
  { name: 'NEET UG',      category: 'Medical',        countryCode: 'IN' },
  { name: 'NEET PG',      category: 'Medical',        countryCode: 'IN' },
  { name: 'JEE Main',     category: 'Engineering',    countryCode: 'IN' },
  { name: 'JEE Advanced', category: 'Engineering',    countryCode: 'IN' },
  { name: 'GATE',         category: 'Tech/PSU',       countryCode: 'IN' },
  { name: 'UPSC CSE',     category: 'Civil Services', countryCode: 'IN' },
  { name: 'IBPS PO',      category: 'Banking',        countryCode: 'IN' },
  { name: 'SSC CGL',      category: 'SSC',            countryCode: 'IN' },
  { name: 'CAT',          category: 'MBA',            countryCode: 'IN' },
  { name: 'CLAT',         category: 'Law',            countryCode: 'IN' },
  { name: 'NDA',          category: 'Defence',        countryCode: 'IN' },
  { name: 'CTET',         category: 'Teaching',       countryCode: 'IN' },
  { name: 'BITSAT',       category: 'Engineering',    countryCode: 'IN' },
  { name: 'AIIMS',        category: 'Medical',        countryCode: 'IN' },
  { name: 'XAT',          category: 'MBA',            countryCode: 'IN' },
];

const BOOKS_DATA = [
  // FICTION
  { title: 'To Kill a Mockingbird', author: 'Harper Lee', category: 'Fiction', condition: 'good', price: 180, type: 'sell', image: cover('9780061996137'), description: 'A gripping tale of racial injustice and childhood innocence in the American South.', sellerInsights: "This book changed my perspective on justice. Atticus Finch is one of literature's greatest moral heroes.", sellerPincode: '400001', ownerIndex: 1 },
  { title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', category: 'Fiction', condition: 'like-new', price: 150, type: 'sell', image: cover('9780743273565'), description: 'A story of the fabulously wealthy Jay Gatsby and his love for Daisy Buchanan.', sellerInsights: "Fitzgerald's prose is pure poetry. Every line is crafted with precision.", sellerPincode: '400001', ownerIndex: 1 },
  { title: '1984', author: 'George Orwell', category: 'Fiction', condition: 'good', price: 140, type: 'both', image: cover('9780141036144'), description: 'A chilling dystopia of totalitarianism, surveillance, and thought control.', sellerInsights: "More relevant today than ever. Doublethink, Newspeak — you'll recognise it all around you.", sellerPincode: '110001', ownerIndex: 2 },
  { title: 'Animal Farm', author: 'George Orwell', category: 'Fiction', condition: 'fair', price: 80, type: 'donate', image: cover('9780451526342'), description: 'A satirical allegory of Soviet totalitarianism through a farm rebellion.', donorNote: 'A short but powerful read — pass it on after you finish!', sellerPincode: '110001', ownerIndex: 2 },
  { title: 'Brave New World', author: 'Aldous Huxley', category: 'Fiction', condition: 'good', price: 160, type: 'sell', image: cover('9780060850524'), description: 'A prophetic novel set in a dystopian future where people are genetically engineered.', sellerInsights: "Huxley predicted smartphones, social media and consumerism decades before they existed.", sellerPincode: '560001', ownerIndex: 3 },
  { title: 'The Alchemist', author: 'Paulo Coelho', category: 'Fiction', condition: 'like-new', price: 200, type: 'sell', image: cover('9780062315007'), description: 'A magical fable about following your dreams and listening to your heart.', sellerInsights: 'Every time I reread this, I find something new. A book for every stage of life.', sellerPincode: '600001', ownerIndex: 4 },
  { title: "Harry Potter and the Philosopher's Stone", author: 'J.K. Rowling', category: 'Fiction', condition: 'good', price: 250, type: 'sell', image: cover('9780439708180'), description: "The magical story of a young wizard's first year at Hogwarts School of Witchcraft.", sellerInsights: "My childhood in a book. Rowling thought of everything.", sellerPincode: '400051', ownerIndex: 5 },
  { title: 'The Hobbit', author: 'J.R.R. Tolkien', category: 'Fiction', condition: 'good', price: 220, type: 'both', image: cover('9780547928227'), description: 'Bilbo Baggins sets out on an epic adventure with a company of dwarves.', sellerInsights: "The perfect introduction to fantasy. Tolkien's world feels absolutely real.", sellerPincode: '411001', ownerIndex: 6 },
  { title: 'Dune', author: 'Frank Herbert', category: 'Fiction', condition: 'like-new', price: 350, type: 'sell', image: cover('9780441013593'), description: 'The epic saga of politics, religion, and ecology on the desert planet Arrakis.', sellerInsights: "The most complex, rewarding sci-fi novel ever written.", sellerPincode: '500001', ownerIndex: 7 },
  { title: "The Hitchhiker's Guide to the Galaxy", author: 'Douglas Adams', category: 'Fiction', condition: 'good', price: 130, type: 'rent', image: cover('9780345391803'), description: 'Moments before Earth is demolished for a hyperspace bypass, Arthur Dent is whisked away.', sellerInsights: "The funniest book I've ever read. The answer is 42.", sellerPincode: '302001', ownerIndex: 8 },
  { title: "Midnight's Children", author: 'Salman Rushdie', category: 'Fiction', condition: 'good', price: 280, type: 'sell', image: cover('9780812976533'), description: "A child born at the moment of India's independence finds his fate tied to the nation.", sellerInsights: "Rushdie's magic realism captures India's chaotic, beautiful soul perfectly.", sellerPincode: '400001', ownerIndex: 1 },
  { title: 'The God of Small Things', author: 'Arundhati Roy', category: 'Fiction', condition: 'fair', price: 100, type: 'donate', image: cover('9780812979657'), description: 'A family in Kerala is torn apart by the Love Laws of Indian society.', donorNote: 'A masterpiece by an Indian author. Please read slowly and savour every sentence.', sellerPincode: '682001', ownerIndex: 9 },
  { title: 'Five Point Someone', author: 'Chetan Bhagat', category: 'Fiction', condition: 'good', price: 120, type: 'sell', image: cover('9788129104595'), description: 'Three friends at IIT struggle with academics, love, and the pressures of Indian society.', sellerInsights: 'Relatable to every Indian student. Light read but hits close to home.', sellerPincode: '110016', ownerIndex: 2 },
  { title: '2 States', author: 'Chetan Bhagat', category: 'Fiction', condition: 'good', price: 110, type: 'sell', image: cover('9788129119001'), description: 'A Punjabi boy and Tamil girl fall in love at IIM Ahmedabad.', sellerInsights: 'Comedy gold. Every Indian in an intercultural relationship will see themselves here.', sellerPincode: '110016', ownerIndex: 2 },
  { title: 'Pride and Prejudice', author: 'Jane Austen', category: 'Fiction', condition: 'like-new', price: 140, type: 'sell', image: cover('9780141439518'), description: "Elizabeth Bennet and Mr. Darcy navigate love and society's expectations in Regency England.", sellerInsights: "Austen's wit is unmatched even 200 years later.", sellerPincode: '560038', ownerIndex: 3 },
  { title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', category: 'Fiction', condition: 'good', price: 180, type: 'both', image: cover('9780140449136'), description: 'A student commits a murder and faces the psychological aftermath.', sellerInsights: "The deepest psychological novel I've read. Dostoevsky gets inside your head.", sellerPincode: '700001', ownerIndex: 4 },
  { title: 'A Suitable Boy', author: 'Vikram Seth', category: 'Fiction', condition: 'fair', price: 200, type: 'sell', image: cover('9780312145521'), description: 'Post-independence India — a mother searches for a suitable husband for her daughter.', sellerInsights: "A 1400-page novel that feels like a short story. Seth makes you live inside 1950s India.", sellerPincode: '400001', ownerIndex: 5 },
  { title: 'Lord of the Flies', author: 'William Golding', category: 'Fiction', condition: 'good', price: 120, type: 'sell', image: cover('9780571295715'), description: 'Stranded British boys descend into savagery on a deserted island.', sellerInsights: 'A disturbing but essential read. Shows how thin the veneer of civilization really is.', sellerPincode: '380001', ownerIndex: 6 },
  { title: 'The Catcher in the Rye', author: 'J.D. Salinger', category: 'Fiction', condition: 'good', price: 150, type: 'rent', image: cover('9780316769174'), description: "Holden Caulfield's rebellious journey through New York after being expelled.", sellerInsights: "The voice of teenage alienation. I re-read this every few years.", sellerPincode: '302001', ownerIndex: 7 },
  { title: 'Sherlock Holmes: The Complete Novels', author: 'Arthur Conan Doyle', category: 'Fiction', condition: 'good', price: 320, type: 'sell', image: cover('9781853260339'), description: 'All four Sherlock Holmes novels in one volume.', sellerInsights: "Holmes is the original rational thinker. His methods hold up brilliantly even today.", sellerPincode: '500001', ownerIndex: 8 },

  // SCIENCE
  { title: 'A Brief History of Time', author: 'Stephen Hawking', category: 'Science', condition: 'good', price: 220, type: 'sell', image: cover('9780553380163'), description: 'Hawking explores the nature of the universe from the Big Bang to black holes.', sellerInsights: 'Made me feel simultaneously tiny and awestruck. Science writing at its absolute best.', sellerPincode: '400001', ownerIndex: 1 },
  { title: 'Sapiens: A Brief History of Humankind', author: 'Yuval Noah Harari', category: 'Science', condition: 'like-new', price: 380, type: 'sell', image: cover('9780062316097'), description: 'How did Homo sapiens come to dominate the Earth? A sweeping history of our species.', sellerInsights: 'Changed how I see money, religion, and human progress. Required reading for everyone.', sellerPincode: '110001', ownerIndex: 2 },
  { title: 'The Selfish Gene', author: 'Richard Dawkins', category: 'Science', condition: 'good', price: 240, type: 'sell', image: cover('9780192860927'), description: "Dawkins introduces the gene's-eye view of evolution and the concept of memes.", sellerInsights: "Completely reshaped my understanding of evolution.", sellerPincode: '560001', ownerIndex: 3 },
  { title: 'Cosmos', author: 'Carl Sagan', category: 'Science', condition: 'fair', price: 160, type: 'donate', image: cover('9780345539434'), description: 'A personal voyage through the universe exploring 15 billion years of cosmic evolution.', donorNote: "Sagan's wonder is contagious. This book made me fall in love with science. Pass it forward!", sellerPincode: '400051', ownerIndex: 4 },
  { title: 'The Gene: An Intimate History', author: 'Siddhartha Mukherjee', category: 'Science', condition: 'like-new', price: 420, type: 'sell', image: cover('9781476733500'), description: 'The story of one of the most powerful and dangerous ideas in the history of science.', sellerInsights: 'Mukherjee writes biology like a novelist. Riveting from page one.', sellerPincode: '700001', ownerIndex: 5 },
  { title: 'Astrophysics for People in a Hurry', author: 'Neil deGrasse Tyson', category: 'Science', condition: 'new', price: 280, type: 'both', image: cover('9780393609394'), description: 'The essential universe in bite-sized chapters for the busy modern reader.', sellerInsights: 'NDT makes the cosmos feel accessible and exciting.', sellerPincode: '411001', ownerIndex: 6 },
  { title: "Surely You're Joking, Mr. Feynman!", author: 'Richard Feynman', category: 'Science', condition: 'good', price: 200, type: 'sell', image: cover('9780393316049'), description: "Adventures of a curious character — the Nobel laureate physicist's hilarious memoirs.", sellerInsights: "The most fun science book ever written. Feynman's curiosity is infectious.", sellerPincode: '500001', ownerIndex: 7 },
  { title: 'Relativity: The Special and General Theory', author: 'Albert Einstein', category: 'Science', condition: 'good', price: 180, type: 'rent', image: cover('9780517884416'), description: "Einstein explains his revolutionary theory in his own words for the general reader.", sellerInsights: "You're reading the original thinker — not a secondhand account.", sellerPincode: '302001', ownerIndex: 8 },
  { title: 'The Double Helix', author: 'James D. Watson', category: 'Science', condition: 'fair', price: 140, type: 'sell', image: cover('9780743216302'), description: 'A candid account of the discovery of the structure of DNA.', sellerInsights: 'The drama behind the discovery is as exciting as any thriller.', sellerPincode: '380001', ownerIndex: 9 },
  { title: 'The Origin of Species', author: 'Charles Darwin', category: 'Science', condition: 'good', price: 160, type: 'sell', image: cover('9780140432053'), description: "Darwin's groundbreaking work presenting evidence for the theory of evolution.", sellerInsights: "The most important science book ever written.", sellerPincode: '600001', ownerIndex: 1 },

  // TECHNOLOGY
  { title: 'Clean Code', author: 'Robert C. Martin', category: 'Technology', condition: 'good', price: 450, type: 'sell', image: cover('9780132350884'), description: 'A handbook of agile software craftsmanship — writing code that is clean and maintainable.', sellerInsights: 'Every single chapter taught me something. I became a noticeably better programmer.', sellerPincode: '400001', ownerIndex: 2 },
  { title: 'The Pragmatic Programmer', author: 'David Thomas & Andrew Hunt', category: 'Technology', condition: 'like-new', price: 480, type: 'both', image: cover('9780135957059'), description: 'From journeyman to master — timeless advice for software developers.', sellerInsights: 'Taught me how to think like a real engineer, not just write code.', sellerPincode: '110001', ownerIndex: 3 },
  { title: 'Design Patterns: Elements of Reusable OO Software', author: 'Gang of Four', category: 'Technology', condition: 'good', price: 580, type: 'sell', image: cover('9780201633610'), description: 'The classic book introducing 23 software design patterns used across the industry.', sellerInsights: 'Dense but essential. After this, you start seeing patterns everywhere.', sellerPincode: '560001', ownerIndex: 4 },
  { title: 'Introduction to Algorithms', author: 'Cormen, Leiserson, Rivest, Stein', category: 'Technology', condition: 'good', price: 750, type: 'sell', image: cover('9780262033848'), description: 'CLRS — the most comprehensive textbook on algorithms and data structures.', sellerInsights: 'This is THE algorithms bible. Cracked many coding interviews with this.', sellerPincode: '400001', ownerIndex: 5, examTagNames: ['GATE'] },
  { title: 'Python Crash Course', author: 'Eric Matthes', category: 'Technology', condition: 'new', price: 350, type: 'both', image: cover('9781593279288'), description: 'A hands-on, project-based introduction to programming in Python.', sellerInsights: 'Perfect for beginners. The projects at the end are genuinely fun to build.', sellerPincode: '700001', ownerIndex: 6 },
  { title: 'JavaScript: The Good Parts', author: 'Douglas Crockford', category: 'Technology', condition: 'fair', price: 200, type: 'donate', image: cover('9780596517748'), description: 'Unearthing the excellent parts of JavaScript.', donorNote: 'Old but gold. The thin book that taught me to write good JS!', sellerPincode: '411001', ownerIndex: 7 },
  { title: 'Computer Networks', author: 'Andrew S. Tanenbaum', category: 'Technology', condition: 'good', price: 520, type: 'sell', image: cover('9780132126953'), description: 'A complete guide to computer networking concepts, protocols, and architectures.', sellerInsights: "The clearest explanation of TCP/IP I've found.", sellerPincode: '500001', ownerIndex: 8, examTagNames: ['GATE'] },
  { title: 'Operating System Concepts', author: 'Silberschatz, Galvin, Gagne', category: 'Technology', condition: 'good', price: 580, type: 'rent', image: cover('9781118063330'), description: 'The "Dinosaur Book" — the definitive guide to modern operating systems.', sellerInsights: 'Essential for CS students. Covers processes, memory, file systems beautifully.', sellerPincode: '302001', ownerIndex: 9, examTagNames: ['GATE'] },
  { title: 'Database System Concepts', author: 'Silberschatz, Korth, Sudarshan', category: 'Technology', condition: 'good', price: 560, type: 'sell', image: cover('9780078022159'), description: 'Comprehensive coverage of database design, query languages, and transaction management.', sellerInsights: 'I cracked 3 DBMS interviews using concepts from this book alone.', sellerPincode: '380001', ownerIndex: 1, examTagNames: ['GATE'] },
  { title: 'Head First Design Patterns', author: 'Eric Freeman & Elisabeth Robson', category: 'Technology', condition: 'like-new', price: 420, type: 'sell', image: cover('9780596007126'), description: "Learn design patterns the fun way — with visual, brain-friendly explanations.", sellerInsights: 'Way more accessible than the GoF book. Great starting point for patterns.', sellerPincode: '600001', ownerIndex: 2 },
  { title: 'Code Complete', author: 'Steve McConnell', category: 'Technology', condition: 'good', price: 500, type: 'sell', image: cover('9780735619678'), description: 'A practical handbook of software construction covering design, coding, and testing.', sellerInsights: 'Massive but worth every page. The chapter on variable naming alone changed my code.', sellerPincode: '110001', ownerIndex: 3 },
  { title: 'The Linux Command Line', author: 'William E. Shotts Jr.', category: 'Technology', condition: 'good', price: 300, type: 'both', image: cover('9781593279523'), description: 'A complete introduction to the Linux command line and shell scripting.', sellerInsights: "Knowing the terminal like this will 10x your productivity.", sellerPincode: '560001', ownerIndex: 4 },

  // HISTORY
  { title: 'India After Gandhi', author: 'Ramachandra Guha', category: 'History', condition: 'good', price: 480, type: 'sell', image: cover('9780060958589'), description: "The most comprehensive history of the world's largest democracy since 1947.", sellerInsights: 'An Indian must-read. Guha dismantles many myths we grew up believing.', sellerPincode: '400001', ownerIndex: 5, examTagNames: ['UPSC CSE'] },
  { title: 'The Discovery of India', author: 'Jawaharlal Nehru', category: 'History', condition: 'fair', price: 250, type: 'sell', image: cover('9780195623598'), description: "Nehru's reflections on India's past, culture, and civilization written from prison.", sellerInsights: 'Understanding modern India requires understanding Nehru. This is the source.', sellerPincode: '110001', ownerIndex: 6, examTagNames: ['UPSC CSE'] },
  { title: 'Freedom at Midnight', author: 'Larry Collins & Dominique Lapierre', category: 'History', condition: 'good', price: 280, type: 'sell', image: cover('9780380006724'), description: 'A gripping account of the events leading up to Indian independence and partition.', sellerInsights: "Reads like a novel. I couldn't put it down.", sellerPincode: '700001', ownerIndex: 7, examTagNames: ['UPSC CSE'] },
  { title: 'Guns, Germs, and Steel', author: 'Jared Diamond', category: 'History', condition: 'good', price: 320, type: 'sell', image: cover('9780393354324'), description: "Why did some civilizations come to dominate others? Diamond's sweeping answer.", sellerInsights: 'Completely changes how you think about human history and development.', sellerPincode: '411001', ownerIndex: 8, examTagNames: ['UPSC CSE'] },
  { title: 'The Silk Roads', author: 'Peter Frankopan', category: 'History', condition: 'like-new', price: 420, type: 'sell', image: cover('9781408839997'), description: "A new history of the world, told from the perspective of Central Asia's trade routes.", sellerInsights: 'Exposes how Eurocentric our history books are. A revelatory read.', sellerPincode: '500001', ownerIndex: 9 },
  { title: 'Homo Deus', author: 'Yuval Noah Harari', category: 'History', condition: 'new', price: 380, type: 'sell', image: cover('9780062464316'), description: 'A brief history of tomorrow — where is humanity heading after conquering famine and disease?', sellerInsights: 'Terrifying and exhilarating in equal measure. The AI chapter hit different after 2023.', sellerPincode: '302001', ownerIndex: 1 },

  // SELF-HELP
  { title: 'Atomic Habits', author: 'James Clear', category: 'Self-Help', condition: 'like-new', price: 320, type: 'sell', image: cover('9780735211292'), description: 'An easy and proven way to build good habits and break bad ones.', sellerInsights: 'The 1% improvement framework genuinely transformed how I structure my day.', sellerPincode: '400001', ownerIndex: 2 },
  { title: 'The 7 Habits of Highly Effective People', author: 'Stephen R. Covey', category: 'Self-Help', condition: 'good', price: 280, type: 'both', image: cover('9781982137274'), description: 'Principle-centered approaches for solving personal problems.', sellerInsights: 'Begin with the end in mind completely reoriented my career goals.', sellerPincode: '110001', ownerIndex: 3 },
  { title: 'How to Win Friends and Influence People', author: 'Dale Carnegie', category: 'Self-Help', condition: 'fair', price: 150, type: 'sell', image: cover('9780671027032'), description: 'Timeless principles for dealing with people and becoming a natural leader.', sellerInsights: "Sounds manipulative but it's genuinely about becoming kinder and more empathetic.", sellerPincode: '560001', ownerIndex: 4 },
  { title: 'Rich Dad Poor Dad', author: 'Robert T. Kiyosaki', category: 'Self-Help', condition: 'good', price: 200, type: 'sell', image: cover('9781612680194'), description: 'What the rich teach their kids about money that the poor and middle class do not.', sellerInsights: 'The asset vs. liability distinction alone is worth reading this book.', sellerPincode: '400051', ownerIndex: 5 },
  { title: "Man's Search for Meaning", author: 'Viktor E. Frankl', category: 'Self-Help', condition: 'good', price: 180, type: 'donate', image: cover('9780807014271'), description: "A Holocaust survivor's account of finding purpose amid extreme suffering.", donorNote: 'This book saved me during the hardest year of my life. I hope it helps you too.', sellerPincode: '700001', ownerIndex: 6 },
  { title: "The Subtle Art of Not Giving a F*ck", author: 'Mark Manson', category: 'Self-Help', condition: 'new', price: 280, type: 'sell', image: cover('9780062457714'), description: 'A counterintuitive approach to living a good life by caring about fewer things.', sellerInsights: 'Cuts through the toxic positivity of most self-help. Refreshingly honest.', sellerPincode: '411001', ownerIndex: 7 },
  { title: 'Deep Work', author: 'Cal Newport', category: 'Self-Help', condition: 'like-new', price: 300, type: 'both', image: cover('9781455586691'), description: 'Rules for focused success in a distracted world.', sellerInsights: 'Put my phone in another room after reading this. Most productive month of my life followed.', sellerPincode: '500001', ownerIndex: 8 },
  { title: 'Ikigai: The Japanese Secret to a Long and Happy Life', author: 'Héctor García', category: 'Self-Help', condition: 'good', price: 250, type: 'sell', image: cover('9780143130727'), description: 'The Japanese concept of ikigai — your reason for being — applied to everyday life.', sellerInsights: 'Short, gentle, and profound. The ikigai Venn diagram made me rethink my career.', sellerPincode: '302001', ownerIndex: 9 },
  { title: 'Think and Grow Rich', author: 'Napoleon Hill', category: 'Self-Help', condition: 'fair', price: 120, type: 'donate', image: cover('9780449214923'), description: 'The original success formula distilled from interviews with 500+ millionaires.', donorNote: 'Timeless classic — share the knowledge, keep the mindset!', sellerPincode: '380001', ownerIndex: 1 },
  { title: 'The Power of Now', author: 'Eckhart Tolle', category: 'Self-Help', condition: 'good', price: 220, type: 'sell', image: cover('9781577314806'), description: 'A guide to spiritual enlightenment — live in the present moment.', sellerInsights: 'Not religious, just deeply practical. The ego chapter alone is mind-opening.', sellerPincode: '600001', ownerIndex: 2 },

  // MEDICINE / NEET
  { title: "Gray's Anatomy for Students", author: 'Richard Drake', category: 'Medicine', condition: 'good', price: 1200, type: 'sell', image: cover('9780702052309'), description: "The world's most trusted anatomy textbook — comprehensive coverage of human anatomy.", sellerInsights: 'Heavy but indispensable for MBBS. The clinical correlations are very exam-friendly.', sellerPincode: '400001', ownerIndex: 3, examTagNames: ['NEET UG', 'NEET PG', 'AIIMS'] },
  { title: "Harrison's Principles of Internal Medicine", author: 'Kasper, Fauci et al.', category: 'Medicine', condition: 'like-new', price: 3500, type: 'rent', image: cover('9780071802154'), description: 'The gold standard reference for internal medicine used by doctors worldwide.', sellerInsights: 'Too heavy to buy if you are a student — renting is smart. Best for NEET PG revision.', sellerPincode: '110001', ownerIndex: 4, examTagNames: ['NEET PG', 'AIIMS'] },
  { title: 'Robbins Basic Pathology', author: 'Kumar, Abbas, Aster', category: 'Medicine', condition: 'good', price: 980, type: 'sell', image: cover('9780323353175'), description: 'Concise, readable overview of pathology — the foundation of clinical medicine.', sellerInsights: 'The diagrams are exceptional. Got me through pathology exams with flying colours.', sellerPincode: '560001', ownerIndex: 5, examTagNames: ['NEET UG', 'NEET PG'] },
  { title: 'Guyton and Hall Medical Physiology', author: 'John E. Hall', category: 'Medicine', condition: 'good', price: 1100, type: 'both', image: cover('9781455770052'), description: "The world's best-selling physiology textbook with clinical vignettes throughout.", sellerInsights: 'Guyton explains cardiac physiology like no one else. My go-to for NEET.', sellerPincode: '400051', ownerIndex: 6, examTagNames: ['NEET UG', 'AIIMS'] },
  { title: 'Pharmacology by Katzung', author: 'Bertram G. Katzung', category: 'Medicine', condition: 'fair', price: 650, type: 'sell', image: cover('9780071825054'), description: 'Basic and clinical pharmacology — comprehensive drug mechanisms and clinical use.', sellerInsights: "Katzung's drug mechanism charts are legendary. Saved me in pharmacology practicals.", sellerPincode: '700001', ownerIndex: 7, examTagNames: ['NEET UG', 'NEET PG'] },
  { title: "Davidson's Principles and Practice of Medicine", author: 'Walker, Colledge et al.', category: 'Medicine', condition: 'good', price: 1400, type: 'rent', image: cover('9780702070280'), description: 'A practical approach to clinical medicine used by students and physicians globally.', sellerInsights: 'My clinical rotations would have been impossible without this. Excellent case studies.', sellerPincode: '411001', ownerIndex: 8, examTagNames: ['NEET PG'] },
  { title: 'Medical Microbiology', author: 'Patrick R. Murray', category: 'Medicine', condition: 'good', price: 780, type: 'sell', image: cover('9780323673228'), description: 'From microbial genetics to host immune response — complete coverage for NEET.', sellerInsights: 'Best for infection and immunity topics. The color plates help identify organisms.', sellerPincode: '500001', ownerIndex: 9, examTagNames: ['NEET UG'] },
  { title: "Snell's Clinical Anatomy by Regions", author: 'Lawrence E. Wineski', category: 'Medicine', condition: 'like-new', price: 850, type: 'sell', image: cover('9781469889467'), description: 'Region-by-region clinical anatomy with high-yield information for exams.', sellerInsights: 'Clinical vignettes at the end of each chapter are pure NEET gold.', sellerPincode: '302001', ownerIndex: 1, examTagNames: ['NEET UG', 'AIIMS'] },
  { title: 'Biochemistry by Stryer', author: 'Jeremy Berg, John Tymoczko', category: 'Medicine', condition: 'good', price: 920, type: 'sell', image: cover('9781429229364'), description: 'Comprehensive biochemistry with stunning molecular illustrations.', sellerInsights: "The Krebs cycle diagrams here are the best I've seen. Made metabolism finally click.", sellerPincode: '380001', ownerIndex: 2, examTagNames: ['NEET UG'] },
  { title: "Bailey & Love's Short Practice of Surgery", author: 'Norman Williams et al.', category: 'Medicine', condition: 'good', price: 1600, type: 'rent', image: cover('9781498796507'), description: 'The most popular general surgery textbook — essential for MBBS and MS aspirants.', sellerInsights: 'Renting makes sense at this price. Perfect for surgery posting and NEET PG prep.', sellerPincode: '600001', ownerIndex: 3, examTagNames: ['NEET PG'] },

  // ENGINEERING / JEE / GATE
  { title: 'Concepts of Physics Vol. 1', author: 'H.C. Verma', category: 'Engineering', condition: 'good', price: 320, type: 'sell', image: olid('8739163'), description: 'The most trusted physics textbook for IIT JEE — crystal-clear theory and problems.', sellerInsights: 'Solved every problem in this book twice. My JEE rank improved dramatically.', sellerPincode: '400001', ownerIndex: 4, examTagNames: ['JEE Main', 'JEE Advanced', 'BITSAT'] },
  { title: 'Concepts of Physics Vol. 2', author: 'H.C. Verma', category: 'Engineering', condition: 'good', price: 320, type: 'sell', image: olid('8739164'), description: 'The second volume covering electrostatics, optics, and modern physics.', sellerInsights: 'Thermodynamics chapter here is exceptional. Vol 1 and 2 together are unbeatable.', sellerPincode: '400001', ownerIndex: 4, examTagNames: ['JEE Main', 'JEE Advanced', 'BITSAT'] },
  { title: 'Problems in General Physics', author: 'I.E. Irodov', category: 'Engineering', condition: 'fair', price: 180, type: 'sell', image: cover('9788183552561'), description: 'A classic Soviet physics problem book — the gold standard for JEE Advanced.', sellerInsights: 'Brutal but rewarding. If you can solve Irodov, JEE Advanced problems feel easy.', sellerPincode: '110001', ownerIndex: 5, examTagNames: ['JEE Advanced'] },
  { title: 'Organic Chemistry', author: 'Morrison & Boyd', category: 'Engineering', condition: 'good', price: 580, type: 'sell', image: cover('9780136436690'), description: 'The definitive organic chemistry reference for JEE — mechanisms made crystal clear.', sellerInsights: 'Every reaction mechanism is explained from first principles. Far better than coaching notes.', sellerPincode: '560001', ownerIndex: 6, examTagNames: ['JEE Main', 'JEE Advanced'] },
  { title: 'Physical Chemistry', author: 'O.P. Tandon', category: 'Engineering', condition: 'good', price: 350, type: 'sell', image: olid('8739165'), description: 'Comprehensive physical chemistry for IIT JEE with solved examples and practice problems.', sellerInsights: 'Electrochemistry and thermodynamics chapters are exceptional.', sellerPincode: '302001', ownerIndex: 7, examTagNames: ['JEE Main', 'JEE Advanced'] },
  { title: 'Engineering Mathematics', author: 'B.S. Grewal', category: 'Engineering', condition: 'good', price: 420, type: 'sell', image: cover('9788174091955'), description: 'Higher Engineering Mathematics — the go-to reference for GATE and university exams.', sellerInsights: 'Every GATE aspirant needs this. Solved examples cover 80% of what GATE asks.', sellerPincode: '411001', ownerIndex: 8, examTagNames: ['GATE'] },
  { title: 'Strength of Materials', author: 'R.K. Bansal', category: 'Engineering', condition: 'fair', price: 280, type: 'sell', image: cover('9788174091901'), description: 'Complete coverage of strength of materials for mechanical engineering students.', sellerInsights: 'Solved thousands of problems from this. Best for GATE Mechanical prep.', sellerPincode: '500001', ownerIndex: 9, examTagNames: ['GATE'] },
  { title: 'Fluid Mechanics and Hydraulic Machines', author: 'R.K. Bansal', category: 'Engineering', condition: 'good', price: 320, type: 'rent', image: olid('8739166'), description: 'Detailed treatment of fluid mechanics principles for GATE Civil/Mechanical.', sellerInsights: "Bernoulli's and continuity equation sections are brilliantly explained.", sellerPincode: '380001', ownerIndex: 1, examTagNames: ['GATE'] },
  { title: 'GATE 2024: Electronics & Communication Engineering', author: 'Made Easy Publications', category: 'Engineering', condition: 'new', price: 650, type: 'sell', image: olid('8739167'), description: 'Comprehensive GATE ECE preparation book with previous year questions and solutions.', sellerInsights: 'The signal & systems section alone is worth the price.', sellerPincode: '600001', ownerIndex: 2, examTagNames: ['GATE'] },
  { title: 'Higher Engineering Mathematics', author: 'H.K. Dass', category: 'Engineering', condition: 'good', price: 380, type: 'both', image: olid('8739168'), description: 'Engineering mathematics for B.Tech, GATE, and UPSC engineering services.', sellerInsights: "Covers Laplace transforms and Fourier series very well.", sellerPincode: '110001', ownerIndex: 3, examTagNames: ['GATE'] },

  // LAW / CLAT
  { title: 'Constitution of India', author: 'P.M. Bakshi', category: 'Law', condition: 'good', price: 280, type: 'sell', image: cover('9788177338300'), description: 'Annotated bare act of the Indian Constitution — essential for CLAT and judicial services.', sellerInsights: 'The annotations are invaluable. Key articles highlighted are perfect for last-minute revision.', sellerPincode: '110001', ownerIndex: 4, examTagNames: ['CLAT', 'UPSC CSE'] },
  { title: 'Introduction to Jurisprudence', author: 'V.D. Mahajan', category: 'Law', condition: 'fair', price: 180, type: 'sell', image: olid('8739169'), description: 'Legal philosophy and theory — the foundations of law explained clearly.', sellerInsights: "Essential for CLAT's legal reasoning section.", sellerPincode: '400001', ownerIndex: 5, examTagNames: ['CLAT'] },
  { title: 'Law of Contracts and Specific Relief', author: 'Avtar Singh', category: 'Law', condition: 'good', price: 350, type: 'sell', image: olid('8739170'), description: 'Complete coverage of contract law under the Indian Contract Act 1872.', sellerInsights: 'Clear explanations with landmark cases. Every aspiring lawyer needs this.', sellerPincode: '560001', ownerIndex: 6, examTagNames: ['CLAT'] },
  { title: 'Indian Penal Code', author: 'Ratanlal & Dhirajlal', category: 'Law', condition: 'good', price: 420, type: 'sell', image: olid('8739171'), description: 'Comprehensive commentary on the Indian Penal Code 1860 with case law.', sellerInsights: 'The case citations are exhaustive and accurate.', sellerPincode: '700001', ownerIndex: 7, examTagNames: ['CLAT', 'UPSC CSE'] },
  { title: 'CLAT 2024: Comprehensive Guide', author: 'Pearson', category: 'Law', condition: 'like-new', price: 580, type: 'sell', image: olid('8739172'), description: 'Complete preparation guide for CLAT with mock tests and previous year papers.', sellerInsights: "The legal GK section is the best I've found.", sellerPincode: '411001', ownerIndex: 8, examTagNames: ['CLAT'] },

  // MBA / CAT / Banking / Other
  { title: 'Quantitative Aptitude for Competitive Examinations', author: 'R.S. Aggarwal', category: 'Other', condition: 'good', price: 320, type: 'sell', image: cover('9789352534029'), description: 'The ultimate QA book for CAT, Banking, SSC — millions of aspirants swear by it.', sellerInsights: 'Solved 3000+ problems from this book. Speed and accuracy improved dramatically.', sellerPincode: '500001', ownerIndex: 9, examTagNames: ['CAT', 'IBPS PO', 'SSC CGL'] },
  { title: 'How to Prepare for the CAT', author: 'Arun Sharma', category: 'Other', condition: 'good', price: 450, type: 'sell', image: olid('8739173'), description: "Arun Sharma's legendary CAT preparation guide — strategy and practice in one book.", sellerInsights: 'The LOD structure is genius. Focus LOD 1-2 for 95%ile, LOD 3 for 99%ile.', sellerPincode: '302001', ownerIndex: 1, examTagNames: ['CAT', 'XAT'] },
  { title: 'Verbal Ability and Reading Comprehension for CAT', author: 'Arun Sharma', category: 'Other', condition: 'like-new', price: 380, type: 'sell', image: olid('8739174'), description: 'Complete verbal ability preparation for CAT with extensive RC practice.', sellerInsights: 'RC strategies in chapter 5 cut my solving time from 20 to 8 minutes per passage.', sellerPincode: '380001', ownerIndex: 2, examTagNames: ['CAT', 'XAT'] },
  { title: 'UPSC Civil Services: GS Paper 1 Study Material', author: 'Drishti IAS', category: 'Other', condition: 'good', price: 550, type: 'sell', image: olid('8739175'), description: 'Comprehensive General Studies Paper 1 covering History, Geography, and Culture.', sellerInsights: 'The Ancient India section here is better than most standard textbooks.', sellerPincode: '110001', ownerIndex: 3, examTagNames: ['UPSC CSE'] },
  { title: 'IBPS PO: Complete Success Package', author: 'Arihant Experts', category: 'Other', condition: 'new', price: 420, type: 'sell', image: olid('8739176'), description: 'All-in-one preparation for IBPS PO with topic-wise practice sets and mock tests.', sellerInsights: 'The banking awareness section is regularly updated. DI sets are realistic.', sellerPincode: '600001', ownerIndex: 4, examTagNames: ['IBPS PO', 'SSC CGL'] },
  { title: "Lucent's General Knowledge", author: 'Lucent Publications', category: 'Other', condition: 'good', price: 180, type: 'sell', image: olid('8739177'), description: 'The most popular GK book for SSC, Banking, Railway, and State PSC exams.', sellerInsights: 'Used this for SSC CGL 2022. Static GK coverage is unmatched at this price point.', sellerPincode: '400001', ownerIndex: 5, examTagNames: ['SSC CGL', 'IBPS PO', 'CTET'] },
  { title: 'NDA/NA Mathematics', author: 'R.S. Aggarwal', category: 'Other', condition: 'good', price: 280, type: 'sell', image: olid('8739178'), description: 'Complete mathematics preparation for NDA/NA exam with 5000+ practice questions.', sellerInsights: 'Matrices and determinants section is the best for NDA prep.', sellerPincode: '302001', ownerIndex: 6, examTagNames: ['NDA'] },
  { title: 'CTET Paper 1 & 2 Guide', author: 'Arihant Experts', category: 'Other', condition: 'like-new', price: 350, type: 'sell', image: olid('8739179'), description: 'Complete preparation guide for CTET with child development, pedagogy, and subject content.', sellerInsights: 'Child development chapters are concise and easy to retain. Mock tests are very accurate.', sellerPincode: '110001', ownerIndex: 7, examTagNames: ['CTET'] },
];

async function seed() {
  await mongoose.connect(env.MONGODB_URI);
  console.log('Connected to MongoDB');

  await Promise.all([User.deleteMany({}), Book.deleteMany({}), ExamTag.deleteMany({}), Address.deleteMany({})]);
  console.log('Cleared existing data');

  const tagDocs = await ExamTag.insertMany(EXAM_TAGS);
  const tagMap  = new Map<string, mongoose.Types.ObjectId>();
  tagDocs.forEach(t => tagMap.set(t.name, t._id as mongoose.Types.ObjectId));
  console.log(`Created ${tagDocs.length} exam tags`);

  const hashed    = await bcrypt.hash('Pass@1234', 12);
  const adminHash = await bcrypt.hash('Admin@123', 12);
  const userDocs  = await User.insertMany(USERS.map((u, i) => ({ ...u, password: i === 0 ? adminHash : hashed })));
  console.log(`Created ${userDocs.length} users`);

  const pincodes = ['400001','110001','560001','700001','600001','411001','500001','302001','380001','110016'];
  const cities   = ['Mumbai','New Delhi','Bangalore','Kolkata','Chennai','Pune','Hyderabad','Jaipur','Ahmedabad','New Delhi'];
  const states   = ['Maharashtra','Delhi','Karnataka','West Bengal','Tamil Nadu','Maharashtra','Telangana','Rajasthan','Gujarat','Delhi'];
  const streets  = ['Flat 4B, Shivaji Nagar, MG Road','House 12, Sector 21, Dwarka','No. 5 Koramangala 4th Block','Apartment 7C, Salt Lake City','Old No. 3 New No. 6, T. Nagar','Baner Road, Near Pune University','Plot 89, Madhapur, HITEC City','C-15 Civil Lines','Satellite Road, Judges Bungalow Area','Block 8, Rohini Sector 3'];

  await Address.insertMany(userDocs.map((u, i) => ({
    user: u._id, fullName: u.name,
    phone: `98${String(1000000000 + i * 111111111).slice(0, 8)}`,
    street: streets[i] || streets[0], city: cities[i] || 'Mumbai',
    state: states[i] || 'Maharashtra', pincode: pincodes[i] || '400001', isDefault: true,
  })));
  console.log('Created addresses');

  const books = BOOKS_DATA.map((b: any) => {
    const { ownerIndex, examTagNames, ...rest } = b;
    return { ...rest, owner: userDocs[ownerIndex]?._id || userDocs[1]._id, examTags: (examTagNames || []).map((n: string) => tagMap.get(n)).filter(Boolean) };
  });

  const bookDocs = await Book.insertMany(books);
  console.log(`Created ${bookDocs.length} books`);

  console.log('\n✅ Seed complete!');
  console.log('─────────────────────────────');
  console.log('Admin: admin@folio.in / Admin@123');
  console.log('User:  rahul@example.in / Pass@1234');
  console.log(`Books: ${bookDocs.length} | Users: ${userDocs.length} | Tags: ${tagDocs.length}`);

  await mongoose.disconnect();
}

seed().catch(err => { console.error(err); process.exit(1); });
